version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: EST
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: scrollreveal
    versions:
    - 4.0.8
